### ISSUE TITLE
Whip Problems with and w/o actual Whips 

### ISSUE THREAD

**Issue by kcerdf123** [minis-patchers/SynWeaponKeywords#14]
Mini, great mod first off. Since the Zedit patcher goes to crap after 255 mods, this was a godsend until this tho. Pastebin of the error: https://pastebin.com/7vCp4R4r This hasn't ever happened before, and I have no idea what caused it. I've tried everything including reinstalling Animated Armoury and uninstalling the no whips mod.

**Comment by kcerdf123** [comment]
Sorry, Mini. False alarm. This was before I noticed I could simply take out whips from the keyword generator you provided (cool feature btw). I'm going to go ahead and close this complaint with a warning to all those that might see this: look at the weapons and keywords you DO have and the ones that you don't before running this patch as that can cause errors like this one.

**Comment by kcerdf123** [comment]
Sorry, Mini. False alarm. This was before I noticed I could simply take out whips from the keyword generator you provided (cool feature btw). I'm going to go ahead and close this complaint with a warning to all those that might see this: look at the weapons and keywords you DO have and the ones that you don't before running this patch as that can cause errors like this one.

**Comment by Minizbot2012** [comment]
This is interesting, It seems that the no whips mod, still has the weapons themselves, but, deletes the keyword from the esp. (It cannot resolve a record, unclean deletion?)... it shouldn't error out like this, and I can likely fix this error given some time... I will note this to look into later, and I preferably want to fix this properly, can you upload a full log?

**Comment by Minizbot2012** [comment]
So my theories on what happened with this: the No Whips mod uses the same ESP name as the original mod; however the difference between original and the No Whips version is simply: a deleted keyword and modified leveled lists The issue that has been causing this is the deleted keyword. The no whips mod leaves an unresolved keyword issue, because there are whips in the esp, however, the weapons are still referencing the keyword that no longer exists, with the updates I just pushed, it should hopefully fix this properly, instead of requiring modification to the DB.
