### ISSUE TITLE
May not be an actual issue - CTD upon loading startup menu options

### ISSUE THREAD

**Issue by Openzmindzz** [minis-patchers/SynWeaponKeywords#18]
Hey, this could be a me problem since I don't see anyone else getting CTD. I am on version 1.6.353 AE. I used Synthesis to create the .esp. It said "Completed". I zip the .esp in a rar then install using Vortex Mod Manager. I deploy my mods, but then I get a crash. I can confirm that created .esp by Synthesis is what is causing the crash. I do have a lot of mods installed, but I doubt those are it, unless they are. So I guess to confirm that, does this work on 1.6.353? Or am I using Synthesis incorrectly?

Also, I don't think this mod covers spears, but my main interest was to give the spears and other weapons from Legacy of the Dragonborn their correct animations from Animated Armory - DAR. Though, the other mods/weapons this patch covers is nice too because I also use all those mods.

**Comment by Minizbot2012** [comment]
Check your installation, bugs like this are usually deeper rooted than things such as esps (check for missing masters, bad skse plugins, due to the recent AE patch, etc). I use this all the time, might be another patcher that's bad, but it is not affecting my AE V1.6.353, and I was just playing earlier today...
